begin;
select plan(4);
select has_function('api', 'consume_rate_limit', array['text','integer','integer'], 'database-backed rate limiter exists');
set local role authenticated;
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000001', true);
select ok(api.consume_rate_limit('test-command', 2, 60), 'first request is allowed');
select ok(api.consume_rate_limit('test-command', 2, 60), 'second request is allowed');
select isnt(api.consume_rate_limit('test-command', 2, 60), true, 'request over the window limit is rejected');
select * from finish();
rollback;
